// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AntDrawer: typeof import('./src/components/AntDrawer.vue')['default']
    AntForm: typeof import('./src/components/AntForm.vue')['default']
    AntFormItem: typeof import('./src/components/AntFormItem.vue')['default']
    AntLayout: typeof import('./src/components/AntLayout.vue')['default']
    AntSearchForm: typeof import('./src/components/AntSearchForm.vue')['default']
    AntTable: typeof import('./src/components/AntTable.vue')['default']
    AntUpload: typeof import('./src/components/AntUpload.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
  }
}

export {}
