// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AntDrawer: typeof import('./src/components/AntDrawer.vue')['default']
    AntForm: typeof import('./src/components/AntForm.vue')['default']
    AntFormItem: typeof import('./src/components/AntFormItem.vue')['default']
    AntLayout: typeof import('./src/components/AntLayout.vue')['default']
    AntSearchForm: typeof import('./src/components/AntSearchForm.vue')['default']
    AntTable: typeof import('./src/components/AntTable.vue')['default']
    AntUpload: typeof import('./src/components/AntUpload.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    FullscreenExitOutlined: typeof import('@ant-design/icons-vue')['FullscreenExitOutlined']
    FullscreenOutlined: typeof import('@ant-design/icons-vue')['FullscreenOutlined']
    LogoutOutlined: typeof import('@ant-design/icons-vue')['LogoutOutlined']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MenuUnfoldOutlined: typeof import('@ant-design/icons-vue')['MenuUnfoldOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}

export {}
